# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id_gminy', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kod_gminy', models.CharField(max_length=42)),
                ('nazwa', models.CharField(max_length=100)),
                ('liczba_obwodów', models.PositiveIntegerField(default=0)),
                ('uprawnionych', models.PositiveIntegerField(default=0)),
                ('kart_wydanych', models.PositiveIntegerField(default=0)),
                ('głosów_oddanych', models.PositiveIntegerField(default=0)),
                ('głosów_nieważnych', models.PositiveIntegerField(default=0)),
                ('głosów_ważnych', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('nazwa', models.CharField(max_length=84, primary_key=True, serialize=False)),
                ('kolor', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat_Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmina', models.PositiveIntegerField()),
                ('liczba_głosów', models.PositiveIntegerField(default=0)),
                ('nazwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadanie2.Kandydat')),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat_Okręg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okręg', models.CharField(max_length=42)),
                ('liczba_głosów', models.PositiveIntegerField(default=0)),
                ('nazwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadanie2.Kandydat')),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat_Województwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('województwo', models.CharField(max_length=42)),
                ('liczba_głosów', models.PositiveIntegerField(default=0)),
                ('nazwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadanie2.Kandydat')),
            ],
        ),
        migrations.CreateModel(
            name='Okręg',
            fields=[
                ('numer', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('liczba_gmin', models.PositiveIntegerField(default=0)),
                ('uprawnionych', models.PositiveIntegerField(default=0)),
                ('kart_wydanych', models.PositiveIntegerField(default=0)),
                ('głosów_oddanych', models.PositiveIntegerField(default=0)),
                ('głosów_nieważnych', models.PositiveIntegerField(default=0)),
                ('głosów_ważnych', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=84)),
            ],
        ),
        migrations.CreateModel(
            name='Województwo',
            fields=[
                ('nazwa_skrót', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=42)),
                ('liczba_okręgów', models.PositiveIntegerField(default=0)),
                ('uprawnionych', models.PositiveIntegerField(default=0)),
                ('kart_wydanych', models.PositiveIntegerField(default=0)),
                ('głosów_oddanych', models.PositiveIntegerField(default=0)),
                ('głosów_nieważnych', models.PositiveIntegerField(default=0)),
                ('głosów_ważnych', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='okręg',
            name='województwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadanie2.Województwo'),
        ),
        migrations.AddField(
            model_name='gmina',
            name='okręg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadanie2.Okręg'),
        ),
        migrations.AlterUniqueTogether(
            name='kandydat_województwo',
            unique_together=set([('województwo', 'nazwa')]),
        ),
        migrations.AlterUniqueTogether(
            name='kandydat_okręg',
            unique_together=set([('okręg', 'nazwa')]),
        ),
        migrations.AlterUniqueTogether(
            name='kandydat_gmina',
            unique_together=set([('gmina', 'nazwa')]),
        ),
        migrations.AlterUniqueTogether(
            name='gmina',
            unique_together=set([('kod_gminy', 'okręg')]),
        ),
    ]
