# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmina',
            name='okręg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kandydat_gmina',
            name='nazwa',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='kandydat_okręg',
            name='nazwa',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='kandydat_okręg',
            name='okręg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kandydat_województwo',
            name='nazwa',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='okręg',
            name='województwo',
            field=models.CharField(max_length=42),
        ),
    ]
